### ISSUE TITLE
Android 9 lacks options menu

### ISSUE THREAD

**Issue by daemonspudguy** [pguyot/Einstein#86]
## Basic Information
There is no options menu for Android 9. 
* Platform (Mac, iOS, Android, Linux, etc): 
* Built from source? (yes/no): both
    * If yes, source branch/revision ID: master
    * If no, release version: March 2019

## Description of issue

The settings are inaccessible. It says "Einstein has stopped" and no notification ever shows up.

## Expected behaviour

Notification with options

## Steps to reproduce issue
Launch app.

**Comment by daemonspudguy** [comment]
Have a logcat: 

`FATAL EXCEPTION: main
Process: com.newtonforever.einstein:remote, PID: 20110
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)`
